import { StyleSheet } from "react-native";

import { palette, paperShadow, paperTexture, webSafeTextShadow } from "../../styles/theme";

export const networkStyles = StyleSheet.create({
  actionMessage: {
    color: palette.green,
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 17,
  },
  actionRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  applicationCard: {
    minWidth: 0,
  },
  bodyText: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
  },
  cardTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  cardOpenArea: {
    gap: 10,
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: "#F5F8FB",
    borderColor: "#DCE3EC",
    borderRadius: 12,
    borderWidth: 1,
    height: 38,
    justifyContent: "center",
    width: 38,
    ...paperShadow("sunken"),
  },
  discoverBody: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 21,
    maxWidth: 520,
  },
  discoverBodyCompact: {
    fontSize: 13,
    lineHeight: 18,
  },
  discoverDashboard: {
    backgroundColor: palette.paper,
    borderBottomColor: "#C9D3E0",
    borderBottomWidth: 1,
    borderColor: "#CFD9E4",
    borderRadius: 12,
    borderWidth: 1,
    gap: 16,
    overflow: "hidden",
    padding: 16,
    ...paperTexture("sheet"),
    ...paperShadow("sheet"),
  },
  discoverDashboardCompact: {
    gap: 10,
    padding: 12,
  },
  discoverDashboardWide: {
    alignItems: "stretch",
    flexDirection: "row",
    padding: 20,
  },
  discoverDashboardMain: {
    flex: 1.25,
    gap: 12,
    minWidth: 0,
  },
  discoverDashboardMainCompact: {
    gap: 8,
  },
  discoverEyebrow: {
    color: palette.teal,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  discoverEyebrowIcon: {
    alignItems: "center",
    backgroundColor: "#0D9488",
    borderBottomColor: "#0A7266",
    borderBottomWidth: 1,
    borderColor: "#2BA79A",
    borderWidth: 1,
    borderRadius: 12,
    height: 34,
    justifyContent: "center",
    width: 34,
    ...paperShadow("cutout"),
  },
  discoverEyebrowIconCompact: {
    height: 30,
    width: 30,
  },
  discoverEyebrowRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
  },
  discoverEyebrowRowCompact: {
    gap: 8,
  },
  discoverSnapshot: {
    backgroundColor: palette.bond,
    borderBottomColor: "#D5DEE8",
    borderBottomWidth: 1,
    borderColor: "#DCE3EC",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    gap: 10,
    minWidth: 280,
    padding: 12,
    ...paperTexture("sheet"),
    ...paperShadow("strip"),
  },
  discoverStat: {
    backgroundColor: palette.bond,
    borderBottomColor: "#D5DEE8",
    borderBottomWidth: 1,
    borderColor: "#D3DCE7",
    borderRadius: 12,
    borderWidth: 1,
    flex: 1,
    minWidth: 112,
    paddingHorizontal: 11,
    paddingVertical: 10,
    ...paperTexture("sheet"),
  },
  discoverStatCompact: {
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  discoverStatLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 14,
    marginTop: 2,
    minWidth: 0,
  },
  discoverStatLabelCompact: {
    fontSize: 10,
    lineHeight: 12,
  },
  discoverStatsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
    marginTop: 2,
  },
  discoverStatsRowCompact: {
    flexWrap: "nowrap",
    gap: 7,
    marginTop: 0,
  },
  discoverStatValue: {
    color: palette.charcoal,
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 24,
    minWidth: 0,
  },
  discoverStatValueCompact: {
    fontSize: 18,
    lineHeight: 21,
  },
  discoverTitle: {
    color: palette.charcoal,
    fontSize: 26,
    fontWeight: "700",
    lineHeight: 32,
    maxWidth: 560,
  },
  discoverTitleCompact: {
    fontSize: 22,
    lineHeight: 27,
  },
  detailPanel: {
    backgroundColor: palette.surface,
    borderBottomColor: "#D2DBE6",
    borderBottomWidth: 1,
    borderColor: "#DCE3EC",
    borderRadius: 12,
    borderWidth: 1,
    gap: 12,
    padding: 14,
    ...paperTexture("sheet"),
    ...paperShadow("sheet"),
  },
  disabled: {
    opacity: 0.58,
  },
  disabledInput: {
    opacity: 0.55,
  },
  entityHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
  },
  entityIcon: {
    alignItems: "center",
    borderRadius: 12,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  errorText: {
    color: palette.red,
  },
  filterChip: {
    alignItems: "center",
    backgroundColor: "#F7F9FC",
    borderColor: "#DCE3EC",
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 36,
    justifyContent: "center",
    paddingHorizontal: 11,
    ...paperShadow("sunken"),
  },
  filterChipActive: {
    backgroundColor: palette.navy,
    borderColor: palette.navy,
    ...paperShadow("pressed"),
  },
  filterChipText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  filterChipTextActive: {
    color: "#FFFFFF",
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  flexField: {
    flex: 1,
    minWidth: 150,
  },
  formInput: {
    backgroundColor: palette.bond,
    borderColor: "#DCE3EC",
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 42,
    paddingHorizontal: 11,
    ...paperShadow("sunken"),
  },
  formField: {
    gap: 6,
  },
  formLabel: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 16,
  },
  formPanel: {
    backgroundColor: palette.surface,
    borderBottomColor: "#D2DBE6",
    borderBottomWidth: 1,
    borderColor: "#DCE3EC",
    borderRadius: 12,
    borderWidth: 1,
    gap: 12,
    padding: 14,
    ...paperTexture("sheet"),
    ...paperShadow("sheet"),
  },
  inlineAction: {
    alignItems: "center",
    backgroundColor: "#0D9488",
    borderBottomColor: "#0A7266",
    borderBottomWidth: 1,
    borderColor: "#2BA79A",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 12,
    ...paperShadow("cutout"),
  },
  inlineActionBalanced: {
    alignSelf: "flex-start",
    minWidth: 104,
  },
  inlineActionSecondary: {
    backgroundColor: palette.bond,
    borderBottomColor: "#D8E0EA",
    borderBottomWidth: 1,
    borderColor: "#DCE3EC",
    ...paperShadow("strip"),
  },
  inlineActionDisabled: {
    borderBottomWidth: 1,
    transform: [{ translateY: 1 }],
  },
  inlineActionDisabledPrimary: {
    backgroundColor: "#D9E1EA",
    borderColor: "#C3CEDB",
    ...paperShadow("sunken"),
  },
  inlineActionDisabledSecondary: {
    backgroundColor: "#E8EDF4",
    borderColor: "#D2DBE6",
    ...paperShadow("sunken"),
  },
  inlineActionWide: {
    alignSelf: "stretch",
    flexGrow: 1,
    minHeight: 44,
    minWidth: 132,
  },
  inlineActionText: {
    color: palette.surface,
    fontSize: 12,
    fontWeight: "700",
    ...webSafeTextShadow({
      color: "rgba(2, 6, 23, 0.2)",
      offset: { height: 1, width: 0 },
      radius: 0,
    }),
  },
  inlineActionTextSecondary: {
    color: palette.text,
    ...webSafeTextShadow({
      color: "rgba(255, 255, 255, 0.5)",
      offset: { height: 1, width: 0 },
      radius: 0,
    }),
  },
  inlineActionTextDisabled: {
    color: "#6B7686",
    ...webSafeTextShadow({
      color: "rgba(255, 255, 255, 0.72)",
      offset: { height: 1, width: 0 },
      radius: 0,
    }),
  },
  inlineState: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  inlineLoadingPanel: {
    alignItems: "center",
    backgroundColor: palette.surface,
    borderBottomColor: "#D9E0EA",
    borderBottomWidth: 1,
    borderColor: "#DCE3EC",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    minHeight: 52,
    paddingHorizontal: 12,
    paddingVertical: 10,
    ...paperTexture("sheet"),
    ...paperShadow("strip"),
  },
  highlightItem: {
    gap: 2,
  },
  highlightList: {
    gap: 8,
  },
  lockedField: {
    backgroundColor: "#E9EEF5",
    borderColor: "#D2DBE6",
    borderRadius: 12,
    borderWidth: 1,
    gap: 3,
    paddingHorizontal: 12,
    paddingVertical: 9,
    ...paperShadow("sunken"),
  },
  lockedFieldText: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 19,
  },
  matchHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
  },
  matchPanel: {
    backgroundColor: "#F0F3F7",
    borderColor: "#DCE3EC",
    borderRadius: 12,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 8,
    ...paperShadow("sunken"),
  },
  matchReason: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
  },
  matchReasons: {
    gap: 3,
  },
  matchSubcopy: {
    color: palette.text,
    flex: 1,
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 15,
  },
  matchSlip: {
    alignItems: "center",
    backgroundColor: palette.buff,
    borderColor: palette.buffBorder,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 29,
    minWidth: 74,
    paddingHorizontal: 9,
    ...paperTexture("sheet"),
    ...paperShadow("strip"),
  },
  matchSlipText: {
    color: palette.amber,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 14,
  },
  mobileStack: {
    gap: 12,
  },
  introPanel: {
    backgroundColor: "#E0F4F0",
    borderColor: "#B6E3DB",
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    ...paperTexture("sheet"),
  },
  introText: {
    color: palette.text,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
  metaRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 6,
  },
  metaText: {
    color: palette.muted,
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  pillWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  permissionText: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 16,
  },
  ownerName: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 19,
  },
  ownerPanel: {
    alignItems: "center",
    backgroundColor: "#F2F5F9",
    borderColor: "#DCE3EC",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 62,
    padding: 10,
    ...paperShadow("sunken"),
  },
  panelIcon: {
    alignItems: "center",
    backgroundColor: "#E0F4F0",
    borderColor: "#B6E3DB",
    borderWidth: 1,
    borderRadius: 12,
    height: 38,
    justifyContent: "center",
    width: 38,
    ...paperShadow("strip"),
  },
  panelList: {
    gap: 8,
  },
  panelTitle: {
    color: palette.text,
    flexShrink: 1,
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 23,
  },
  panelTitleRow: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 10,
    minWidth: 0,
  },
  profileMetaGrid: {
    gap: 8,
  },
  profileMetaItem: {
    alignItems: "center",
    backgroundColor: "#F2F5F9",
    borderColor: "#DCE3EC",
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: "row",
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 10,
    ...paperShadow("sunken"),
  },
  profileName: {
    color: palette.text,
    fontSize: 22,
    fontWeight: "700",
    lineHeight: 28,
    marginTop: 2,
  },
  profileEntityIcon: {
    backgroundColor: "#EBF2FE",
    borderColor: "#C9DAF5",
    borderWidth: 1,
    ...paperShadow("strip"),
  },
  portfolioListRow: {
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  portfolioRowBody: {
    minWidth: 170,
  },
  resumeIcon: {
    alignItems: "center",
    backgroundColor: "#EBF2FE",
    borderColor: "#C9DAF5",
    borderWidth: 1,
    borderRadius: 12,
    height: 42,
    justifyContent: "center",
    width: 42,
    ...paperShadow("strip"),
  },
  networkCard: {
    backgroundColor: palette.bond,
    borderBottomColor: "#D2DBE6",
    borderBottomWidth: 1,
    borderColor: "#DCE3EC",
    gap: 12,
    minWidth: 0,
    ...paperTexture("sheet"),
    ...paperShadow("sheet"),
  },
  networkCardWide: {
    flexBasis: 300,
    flexGrow: 0,
    maxWidth: 326,
    minWidth: 286,
  },
  rowActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "flex-end",
  },
  searchRowCompact: {
    minHeight: 46,
    paddingHorizontal: 12,
  },
  sectionActionsRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  skillIcon: {
    alignItems: "center",
    backgroundColor: "#E6F4EC",
    borderColor: "#BEE0C9",
    borderWidth: 1,
    borderRadius: 12,
    height: 42,
    justifyContent: "center",
    width: 42,
    ...paperShadow("strip"),
  },
  skillPill: {
    alignItems: "center",
    backgroundColor: "#EDF1F7",
    borderColor: "#CED8E3",
    borderRadius: 3,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    minHeight: 26,
    justifyContent: "center",
    paddingRight: 8,
    ...paperTexture("sheet"),
    ...paperShadow("strip"),
  },
  skillPillEdge: {
    alignSelf: "stretch",
    backgroundColor: "#D5DEE8",
    borderRightColor: "rgba(255, 255, 255, 0.54)",
    borderRightWidth: 1,
    width: 4,
  },
  skillPillText: {
    color: palette.text,
    fontSize: 11,
    fontWeight: "700",
  },
  snapshotAction: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  snapshotAvatar: {
    alignItems: "center",
    backgroundColor: "#EBF2FE",
    borderColor: "#C9DAF5",
    borderWidth: 1,
    borderRadius: 12,
    height: 38,
    justifyContent: "center",
    width: 38,
    ...paperShadow("strip"),
  },
  snapshotAvatarMentor: {
    backgroundColor: "#F1EBFE",
    borderColor: "#D9CAFB",
  },
  snapshotEmpty: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  snapshotHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  snapshotList: {
    gap: 8,
  },
  snapshotMeta: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
  },
  snapshotName: {
    color: palette.text,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 17,
  },
  snapshotRow: {
    alignItems: "center",
    backgroundColor: "#F7F9FC",
    borderBottomColor: "#CED8E3",
    borderBottomWidth: 1,
    borderColor: "#D8E0EA",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    minHeight: 58,
    padding: 9,
    ...paperTexture("sheet"),
  },
  snapshotTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "700",
  },
  statusStack: {
    alignItems: "flex-end",
    gap: 6,
  },
  statusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  textArea: {
    minHeight: 96,
    paddingTop: 12,
  },
  chatComposer: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 8,
  },
  chatComposerInput: {
    flex: 1,
    minWidth: 0,
  },
  chatList: {
    gap: 8,
  },
  chatBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#F2F5F9",
    borderColor: "#DCE3EC",
    borderRadius: 10,
    borderWidth: 1,
    gap: 2,
    maxWidth: "86%",
    paddingHorizontal: 12,
    paddingVertical: 8,
    ...paperShadow("sunken"),
  },
  chatBubbleMine: {
    alignSelf: "flex-end",
    backgroundColor: "#E0F4F0",
    borderColor: "#B6E3DB",
  },
  chatBubbleText: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
  },
  chatBubbleMeta: {
    color: palette.faint,
    fontSize: 11,
    fontWeight: "700",
  },
  requestNote: {
    backgroundColor: "#F2F5F9",
    borderColor: "#DCE3EC",
    borderLeftColor: "#2BA79A",
    borderLeftWidth: 3,
    borderRadius: 12,
    borderWidth: 1,
    marginTop: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  requestNoteText: {
    color: palette.muted,
    fontSize: 13,
    fontStyle: "italic",
    fontWeight: "600",
    lineHeight: 18,
  },
  unreadBadge: {
    alignItems: "center",
    backgroundColor: "#DC2626",
    borderRadius: 10,
    justifyContent: "center",
    minWidth: 20,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  unreadBadgeText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "700",
  },
  toolbar: {
    alignItems: "flex-start",
    gap: 10,
  },
  toolbarWide: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
  },
  twoColumn: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
});
