import { Platform, StyleSheet, type ViewStyle } from "react-native";

import { fonts, palette, paperShadow, radii } from "../../styles/theme";

// Clears the coloured glow that primary actions carry, for secondary and
// disabled variants.
const noShadow: ViewStyle =
  Platform.OS === "web" ? ({ boxShadow: "none" } as ViewStyle) : { elevation: 0, shadowOpacity: 0 };

export const networkStyles = StyleSheet.create({
  // styles.card is flex: 1, which makes stacked cards split the available
  // height equally and clips longer ones; this sizes a card to its content.
  contentSizedCard: {
    flexBasis: "auto",
    flexGrow: 0,
    flexShrink: 0,
  },
  actionMessage: {
    color: palette.green,
    fontFamily: fonts.semibold,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  actionRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 4,
  },
  applicationCard: {
    minWidth: 0,
  },
  applicationOpenArea: {
    gap: 12,
  },
  bodyText: {
    color: palette.text,
    fontFamily: fonts.regular,
    fontSize: 15,
    lineHeight: 23,
  },
  cardTitleBlock: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  cardOpenArea: {
    gap: 12,
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: palette.surfaceAlt,
    borderRadius: radii.pill,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  discoverBody: {
    color: palette.muted,
    fontFamily: fonts.medium,
    fontSize: 14,
    lineHeight: 21,
    maxWidth: 520,
  },
  discoverBodyCompact: {
    fontSize: 13,
    lineHeight: 18,
  },
  discoverDashboard: {
    backgroundColor: palette.surface,
    borderColor: palette.hairline,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: 16,
    overflow: "hidden",
    padding: 18,
    ...paperShadow("sheet"),
  },
  discoverDashboardCompact: {
    gap: 10,
    padding: 12,
  },
  discoverDashboardWide: {
    alignItems: "stretch",
    flexDirection: "row",
    padding: 20,
  },
  discoverDashboardMain: {
    flex: 1.25,
    gap: 12,
    minWidth: 0,
  },
  discoverDashboardMainCompact: {
    gap: 8,
  },
  discoverEyebrow: {
    color: palette.caspian,
    fontFamily: fonts.bold,
    fontSize: 12,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  discoverEyebrowIcon: {
    alignItems: "center",
    backgroundColor: palette.caspian,
    borderRadius: radii.md,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  discoverEyebrowIconCompact: {
    height: 30,
    width: 30,
  },
  discoverEyebrowRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
  },
  discoverEyebrowRowCompact: {
    gap: 8,
  },
  discoverSnapshot: {
    flex: 1,
    gap: 10,
    minWidth: 280,
  },
  discoverStat: {
    backgroundColor: palette.surfaceAlt,
    borderRadius: radii.md,
    flex: 1,
    minWidth: 112,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  discoverStatCompact: {
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  discoverStatLabel: {
    color: palette.muted,
    fontFamily: fonts.semibold,
    fontSize: 11,
    lineHeight: 14,
    marginTop: 2,
    minWidth: 0,
  },
  discoverStatLabelCompact: {
    fontSize: 10,
    lineHeight: 12,
  },
  discoverStatsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
    marginTop: 2,
  },
  discoverStatsRowCompact: {
    flexWrap: "nowrap",
    gap: 7,
    marginTop: 0,
  },
  discoverStatValue: {
    color: palette.text,
    fontFamily: fonts.extrabold,
    fontSize: 20,
    lineHeight: 24,
    minWidth: 0,
  },
  discoverStatValueCompact: {
    fontSize: 18,
    lineHeight: 21,
  },
  discoverTitle: {
    color: palette.text,
    fontFamily: fonts.extrabold,
    fontSize: 26,
    letterSpacing: -0.4,
    lineHeight: 32,
    maxWidth: 560,
  },
  discoverTitleCompact: {
    fontSize: 22,
    lineHeight: 27,
  },
  detailPanel: {
    gap: 16,
  },
  disabled: {
    opacity: 0.6,
  },
  disabledInput: {
    opacity: 0.55,
  },
  entityHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
  },
  entityIcon: {
    alignItems: "center",
    borderRadius: radii.md,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  errorText: {
    color: palette.red,
  },
  filterChip: {
    alignItems: "center",
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 44,
    minWidth: 44,
    paddingHorizontal: 16,
  },
  filterChipActive: {
    backgroundColor: palette.navy,
    borderColor: palette.navy,
  },
  filterChipText: {
    color: palette.text,
    fontFamily: fonts.semibold,
    fontSize: 13,
  },
  filterChipTextActive: {
    color: "#FFFFFF",
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  flexField: {
    flex: 1,
    minWidth: 150,
  },
  formInput: {
    backgroundColor: palette.surface,
    // 3:1 against the surrounding surface so the field edge is perceivable
    // (WCAG 1.4.11).
    borderColor: palette.fieldBorder,
    borderRadius: radii.md,
    borderWidth: 1,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  formField: {
    gap: 7,
  },
  formLabel: {
    color: palette.text,
    fontFamily: fonts.semibold,
    fontSize: 13,
    lineHeight: 17,
  },
  formPanel: {
    backgroundColor: palette.surface,
    borderColor: palette.hairline,
    borderRadius: radii.lg,
    borderWidth: 1,
    gap: 14,
    padding: 18,
    ...paperShadow("sheet"),
  },
  inlineAction: {
    alignItems: "center",
    backgroundColor: palette.caspian,
    borderRadius: radii.md,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    minHeight: 46,
    minWidth: 44,
    paddingHorizontal: 16,
    ...paperShadow("cutout"),
  },
  inlineActionBalanced: {
    alignSelf: "flex-start",
    minWidth: 112,
  },
  inlineActionSecondary: {
    backgroundColor: palette.surfaceAlt,
    ...noShadow,
  },
  inlineActionDisabled: {
    ...noShadow,
  },
  inlineActionDisabledPrimary: {
    backgroundColor: "#E4DED3",
  },
  inlineActionDisabledSecondary: {
    backgroundColor: "#EEE9E0",
  },
  inlineActionWide: {
    alignSelf: "stretch",
    flexGrow: 1,
    minHeight: 46,
    minWidth: 132,
  },
  inlineActionText: {
    color: palette.surface,
    fontFamily: fonts.semibold,
    fontSize: 14,
  },
  inlineActionTextSecondary: {
    color: palette.text,
  },
  inlineActionTextDisabled: {
    color: "#5E6270",
  },
  inlineState: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  inlineLoadingPanel: {
    alignItems: "center",
    backgroundColor: palette.surface,
    borderColor: palette.hairline,
    borderRadius: radii.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 10,
    ...paperShadow("strip"),
  },
  highlightItem: {
    backgroundColor: palette.surfaceAlt,
    borderRadius: radii.md,
    gap: 2,
    padding: 12,
  },
  highlightList: {
    gap: 8,
  },
  lockedField: {
    backgroundColor: palette.surfaceAlt,
    borderRadius: radii.md,
    gap: 3,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  lockedFieldText: {
    color: palette.text,
    fontFamily: fonts.semibold,
    fontSize: 15,
    lineHeight: 20,
  },
  matchHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  matchPanel: {
    backgroundColor: "#FBF6EC",
    borderRadius: radii.md,
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  matchReason: {
    color: palette.muted,
    fontFamily: fonts.semibold,
    fontSize: 12,
    lineHeight: 16,
  },
  matchReasons: {
    gap: 3,
  },
  matchSubcopy: {
    color: palette.text,
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: 12,
    lineHeight: 16,
  },
  matchSlip: {
    alignItems: "center",
    backgroundColor: palette.buff,
    borderColor: palette.buffBorder,
    borderRadius: radii.pill,
    borderWidth: 1,
    flexDirection: "row",
    gap: 5,
    justifyContent: "center",
    minHeight: 28,
    paddingHorizontal: 10,
  },
  matchSlipQuiet: {
    backgroundColor: palette.surface,
    borderColor: palette.border,
  },
  matchSlipText: {
    color: palette.amber,
    fontFamily: fonts.bold,
    fontSize: 12,
    lineHeight: 15,
  },
  matchSlipTextQuiet: {
    color: palette.muted,
  },
  mobileStack: {
    gap: 12,
  },
  introPanel: {
    backgroundColor: palette.caspianSoft,
    borderRadius: radii.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  introText: {
    color: palette.text,
    fontFamily: fonts.medium,
    fontSize: 14,
    lineHeight: 20,
  },
  metaRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
  },
  metaText: {
    color: palette.muted,
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: 13,
    lineHeight: 18,
  },
  pillWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  permissionText: {
    color: palette.muted,
    fontFamily: fonts.semibold,
    fontSize: 11,
    lineHeight: 16,
  },
  ownerName: {
    color: palette.text,
    fontFamily: fonts.bold,
    fontSize: 15,
    lineHeight: 20,
  },
  ownerPanel: {
    alignItems: "center",
    backgroundColor: palette.surfaceAlt,
    borderRadius: radii.lg,
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    padding: 12,
  },
  panelIcon: {
    alignItems: "center",
    backgroundColor: palette.caspianSoft,
    borderRadius: radii.pill,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  panelList: {
    gap: 10,
  },
  panelTitle: {
    color: palette.text,
    flexShrink: 1,
    fontFamily: fonts.extrabold,
    fontSize: 22,
    letterSpacing: -0.4,
    lineHeight: 28,
  },
  panelTitleRow: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 12,
    minWidth: 0,
  },
  profileMetaGrid: {
    gap: 6,
  },
  profileMetaItem: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    minHeight: 30,
  },
  profileName: {
    color: palette.text,
    fontFamily: fonts.extrabold,
    fontSize: 24,
    letterSpacing: -0.4,
    lineHeight: 30,
    marginTop: 2,
  },
  profileEntityIcon: {
    backgroundColor: palette.caspianSoft,
  },
  portfolioListRow: {
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  portfolioRowBody: {
    minWidth: 170,
  },
  resumeIcon: {
    alignItems: "center",
    backgroundColor: palette.caspianSoft,
    borderRadius: radii.md,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  networkCard: {
    gap: 14,
    minWidth: 0,
  },
  networkCardWide: {
    flexBasis: 300,
    flexGrow: 0,
    maxWidth: 326,
    minWidth: 286,
  },
  rowActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "flex-end",
  },
  searchRowCompact: {
    minHeight: 50,
    paddingHorizontal: 16,
  },
  sectionActionsRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  skillIcon: {
    alignItems: "center",
    backgroundColor: palette.greenSoft,
    borderRadius: radii.md,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  skillPill: {
    alignItems: "center",
    backgroundColor: palette.surfaceAlt,
    borderRadius: radii.pill,
    flexDirection: "row",
    justifyContent: "center",
    minHeight: 28,
    paddingHorizontal: 11,
  },
  skillPillEdge: {
    display: "none",
  },
  skillPillText: {
    color: palette.text,
    fontFamily: fonts.medium,
    fontSize: 12,
  },
  snapshotAction: {
    color: palette.muted,
    fontFamily: fonts.semibold,
    fontSize: 12,
  },
  snapshotAvatar: {
    alignItems: "center",
    backgroundColor: palette.caspianSoft,
    borderRadius: radii.pill,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  snapshotAvatarMentor: {
    backgroundColor: palette.violetSoft,
  },
  snapshotEmpty: {
    color: palette.muted,
    fontFamily: fonts.medium,
    fontSize: 13,
    lineHeight: 18,
  },
  snapshotHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  snapshotList: {
    gap: 8,
  },
  snapshotMeta: {
    color: palette.muted,
    fontFamily: fonts.medium,
    fontSize: 12,
    lineHeight: 16,
  },
  snapshotName: {
    color: palette.text,
    fontFamily: fonts.bold,
    fontSize: 14,
    lineHeight: 18,
  },
  snapshotRow: {
    alignItems: "center",
    backgroundColor: palette.surfaceAlt,
    borderRadius: radii.md,
    flexDirection: "row",
    gap: 10,
    minHeight: 58,
    padding: 10,
  },
  snapshotTitle: {
    color: palette.text,
    fontFamily: fonts.bold,
    fontSize: 15,
  },
  statusStack: {
    alignItems: "flex-end",
    gap: 6,
  },
  statusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  textArea: {
    minHeight: 104,
    paddingTop: 12,
  },
  chatComposer: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 8,
  },
  chatComposerInput: {
    flex: 1,
    minWidth: 0,
  },
  chatList: {
    gap: 8,
  },
  chatBubble: {
    alignSelf: "flex-start",
    backgroundColor: palette.surfaceAlt,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 18,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    gap: 3,
    maxWidth: "86%",
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  chatBubbleMine: {
    alignSelf: "flex-end",
    backgroundColor: palette.caspianSoft,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 6,
  },
  chatBubbleText: {
    color: palette.text,
    fontFamily: fonts.regular,
    fontSize: 15,
    lineHeight: 21,
  },
  chatBubbleMeta: {
    color: palette.muted,
    fontFamily: fonts.medium,
    fontSize: 11,
  },
  requestNote: {
    backgroundColor: palette.surfaceAlt,
    borderLeftColor: palette.saffron,
    borderLeftWidth: 3,
    borderRadius: radii.md,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  requestNoteText: {
    color: palette.muted,
    fontFamily: fonts.regular,
    fontSize: 14,
    fontStyle: "italic",
    lineHeight: 20,
  },
  unreadBadge: {
    alignItems: "center",
    backgroundColor: palette.pomegranate,
    borderRadius: radii.pill,
    justifyContent: "center",
    minWidth: 22,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  unreadBadgeText: {
    color: "#FFFFFF",
    fontFamily: fonts.bold,
    fontSize: 11,
  },
  toolbar: {
    alignItems: "flex-start",
    gap: 12,
  },
  toolbarWide: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
  },
  twoColumn: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
});
