import { StyleSheet } from "react-native";

import { palette, paperShadow, paperTexture, webSafeTextShadow } from "../../styles/theme";

export const networkStyles = StyleSheet.create({
  actionMessage: {
    color: palette.green,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  actionRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  applicationCard: {
    minWidth: 0,
  },
  bodyText: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
  },
  cardTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  cardOpenArea: {
    gap: 10,
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: "#FAF4EA",
    borderColor: "#D8CDC0",
    borderRadius: 8,
    borderWidth: 1,
    height: 38,
    justifyContent: "center",
    width: 38,
    ...paperShadow("sunken"),
  },
  discoverBody: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 21,
    maxWidth: 520,
  },
  discoverBodyCompact: {
    fontSize: 13,
    lineHeight: 18,
  },
  discoverDashboard: {
    backgroundColor: palette.paper,
    borderBottomColor: "#CFC1AF",
    borderBottomWidth: 3,
    borderColor: "#D9CCBA",
    borderRadius: 8,
    borderWidth: 1,
    gap: 16,
    overflow: "hidden",
    padding: 16,
    ...paperTexture("sheet"),
    ...paperShadow("sheet"),
  },
  discoverDashboardCompact: {
    gap: 10,
    padding: 12,
  },
  discoverDashboardWide: {
    alignItems: "stretch",
    flexDirection: "row",
    padding: 20,
  },
  discoverDashboardMain: {
    flex: 1.25,
    gap: 12,
    minWidth: 0,
  },
  discoverDashboardMainCompact: {
    gap: 8,
  },
  discoverEyebrow: {
    color: palette.teal,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  discoverEyebrowIcon: {
    alignItems: "center",
    backgroundColor: "#087568",
    borderBottomColor: "#075B55",
    borderBottomWidth: 3,
    borderColor: "#0A8A7A",
    borderWidth: 1,
    borderRadius: 8,
    height: 34,
    justifyContent: "center",
    width: 34,
    ...paperShadow("cutout"),
  },
  discoverEyebrowIconCompact: {
    height: 30,
    width: 30,
  },
  discoverEyebrowRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
  },
  discoverEyebrowRowCompact: {
    gap: 8,
  },
  discoverSnapshot: {
    backgroundColor: palette.bond,
    borderBottomColor: "#D6C9B8",
    borderBottomWidth: 3,
    borderColor: "#DCD0C0",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 10,
    minWidth: 280,
    padding: 12,
    ...paperTexture("sheet"),
    ...paperShadow("strip"),
  },
  discoverStat: {
    backgroundColor: palette.bond,
    borderBottomColor: "#D7C9B8",
    borderBottomWidth: 2,
    borderColor: "#DED2C1",
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minWidth: 112,
    paddingHorizontal: 11,
    paddingVertical: 10,
    ...paperTexture("sheet"),
  },
  discoverStatCompact: {
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  discoverStatLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 14,
    marginTop: 2,
    minWidth: 0,
  },
  discoverStatLabelCompact: {
    fontSize: 10,
    lineHeight: 12,
  },
  discoverStatsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 9,
    marginTop: 2,
  },
  discoverStatsRowCompact: {
    flexWrap: "nowrap",
    gap: 7,
    marginTop: 0,
  },
  discoverStatValue: {
    color: palette.charcoal,
    fontSize: 20,
    fontWeight: "900",
    lineHeight: 24,
    minWidth: 0,
  },
  discoverStatValueCompact: {
    fontSize: 18,
    lineHeight: 21,
  },
  discoverTitle: {
    color: palette.charcoal,
    fontSize: 26,
    fontWeight: "900",
    lineHeight: 32,
    maxWidth: 560,
  },
  discoverTitleCompact: {
    fontSize: 22,
    lineHeight: 27,
  },
  detailPanel: {
    backgroundColor: palette.surface,
    borderBottomColor: "#D2C5B7",
    borderBottomWidth: 3,
    borderColor: "#D9CDC0",
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
    ...paperTexture("sheet"),
    ...paperShadow("sheet"),
  },
  disabled: {
    opacity: 0.58,
  },
  disabledInput: {
    opacity: 0.55,
  },
  entityHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
  },
  entityIcon: {
    alignItems: "center",
    borderRadius: 8,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  errorText: {
    color: palette.red,
  },
  filterChip: {
    alignItems: "center",
    backgroundColor: "#FBF6EE",
    borderColor: "#DCD1C3",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 36,
    justifyContent: "center",
    paddingHorizontal: 11,
    ...paperShadow("sunken"),
  },
  filterChipActive: {
    backgroundColor: "#E8DECF",
    borderColor: "#C8B8A5",
    ...paperShadow("pressed"),
  },
  filterChipText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "900",
  },
  filterChipTextActive: {
    color: palette.charcoal,
  },
  filterRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  flexField: {
    flex: 1,
    minWidth: 150,
  },
  formInput: {
    backgroundColor: palette.bond,
    borderColor: "#D8CDC0",
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 42,
    paddingHorizontal: 11,
    ...paperShadow("sunken"),
  },
  formField: {
    gap: 6,
  },
  formLabel: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 16,
  },
  formPanel: {
    backgroundColor: palette.surface,
    borderBottomColor: "#D2C5B7",
    borderBottomWidth: 3,
    borderColor: "#D9CDC0",
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
    ...paperTexture("sheet"),
    ...paperShadow("sheet"),
  },
  inlineAction: {
    alignItems: "center",
    backgroundColor: "#087568",
    borderBottomColor: "#075B55",
    borderBottomWidth: 3,
    borderColor: "#0A8A7A",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    minHeight: 36,
    paddingHorizontal: 12,
    ...paperShadow("cutout"),
  },
  inlineActionBalanced: {
    alignSelf: "flex-start",
    minWidth: 104,
  },
  inlineActionSecondary: {
    backgroundColor: palette.bond,
    borderBottomColor: "#D6CABB",
    borderBottomWidth: 2,
    borderColor: "#D8CDC0",
    ...paperShadow("strip"),
  },
  inlineActionDisabled: {
    borderBottomWidth: 1,
    transform: [{ translateY: 1 }],
  },
  inlineActionDisabledPrimary: {
    backgroundColor: "#DFD7CB",
    borderColor: "#C8BAAA",
    ...paperShadow("sunken"),
  },
  inlineActionDisabledSecondary: {
    backgroundColor: "#EEE7DC",
    borderColor: "#D0C4B5",
    ...paperShadow("sunken"),
  },
  inlineActionWide: {
    alignSelf: "stretch",
    flexGrow: 1,
    minHeight: 44,
    minWidth: 132,
  },
  inlineActionText: {
    color: palette.surface,
    fontSize: 12,
    fontWeight: "900",
    ...webSafeTextShadow({
      color: "rgba(2, 6, 23, 0.2)",
      offset: { height: 1, width: 0 },
      radius: 0,
    }),
  },
  inlineActionTextSecondary: {
    color: palette.text,
    ...webSafeTextShadow({
      color: "rgba(255, 255, 255, 0.5)",
      offset: { height: 1, width: 0 },
      radius: 0,
    }),
  },
  inlineActionTextDisabled: {
    color: "#746D62",
    ...webSafeTextShadow({
      color: "rgba(255, 255, 255, 0.72)",
      offset: { height: 1, width: 0 },
      radius: 0,
    }),
  },
  inlineState: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  inlineLoadingPanel: {
    alignItems: "center",
    backgroundColor: palette.surface,
    borderBottomColor: "#D7CBBE",
    borderBottomWidth: 2,
    borderColor: "#DCD1C3",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    minHeight: 52,
    paddingHorizontal: 12,
    paddingVertical: 10,
    ...paperTexture("sheet"),
    ...paperShadow("strip"),
  },
  highlightItem: {
    gap: 2,
  },
  highlightList: {
    gap: 8,
  },
  lockedField: {
    backgroundColor: "#F0E8DC",
    borderColor: "#D2C6B7",
    borderRadius: 8,
    borderWidth: 1,
    gap: 3,
    paddingHorizontal: 12,
    paddingVertical: 9,
    ...paperShadow("sunken"),
  },
  lockedFieldText: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 19,
  },
  matchHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 8,
  },
  matchPanel: {
    backgroundColor: "#F4EFE6",
    borderColor: "#D9CDC0",
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 8,
    ...paperShadow("sunken"),
  },
  matchReason: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
  },
  matchReasons: {
    gap: 3,
  },
  matchSubcopy: {
    color: palette.text,
    flex: 1,
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 15,
  },
  matchSlip: {
    alignItems: "center",
    backgroundColor: palette.buff,
    borderColor: palette.buffBorder,
    borderRadius: 5,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 29,
    minWidth: 74,
    paddingHorizontal: 9,
    ...paperTexture("sheet"),
    ...paperShadow("strip"),
  },
  matchSlipText: {
    color: palette.amber,
    fontSize: 11,
    fontWeight: "900",
    lineHeight: 14,
  },
  mobileStack: {
    gap: 12,
  },
  introPanel: {
    backgroundColor: "#E7F2EE",
    borderColor: "#B9DCD4",
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    ...paperTexture("sheet"),
  },
  introText: {
    color: palette.text,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
  metaRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 6,
  },
  metaText: {
    color: palette.muted,
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  pillWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  permissionText: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 16,
  },
  ownerName: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 19,
  },
  ownerPanel: {
    alignItems: "center",
    backgroundColor: "#F7F1E7",
    borderColor: "#D9CDC0",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 62,
    padding: 10,
    ...paperShadow("sunken"),
  },
  panelIcon: {
    alignItems: "center",
    backgroundColor: "#E7F2EE",
    borderColor: "#B9DCD4",
    borderWidth: 1,
    borderRadius: 8,
    height: 38,
    justifyContent: "center",
    width: 38,
    ...paperShadow("strip"),
  },
  panelList: {
    gap: 8,
  },
  panelTitle: {
    color: palette.text,
    flexShrink: 1,
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 23,
  },
  panelTitleRow: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 10,
    minWidth: 0,
  },
  profileMetaGrid: {
    gap: 8,
  },
  profileMetaItem: {
    alignItems: "center",
    backgroundColor: "#F7F1E7",
    borderColor: "#DCD1C3",
    borderWidth: 1,
    borderRadius: 8,
    flexDirection: "row",
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 10,
    ...paperShadow("sunken"),
  },
  profileName: {
    color: palette.text,
    fontSize: 22,
    fontWeight: "900",
    lineHeight: 28,
    marginTop: 2,
  },
  profileEntityIcon: {
    backgroundColor: "#EAF2FF",
    borderColor: "#D2DDF1",
    borderWidth: 1,
    ...paperShadow("strip"),
  },
  portfolioListRow: {
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  portfolioRowBody: {
    minWidth: 170,
  },
  resumeIcon: {
    alignItems: "center",
    backgroundColor: "#EAF2FF",
    borderColor: "#D2DDF1",
    borderWidth: 1,
    borderRadius: 8,
    height: 42,
    justifyContent: "center",
    width: 42,
    ...paperShadow("strip"),
  },
  networkCard: {
    backgroundColor: palette.bond,
    borderBottomColor: "#D0C4B5",
    borderBottomWidth: 3,
    borderColor: "#D8CDC0",
    gap: 12,
    minWidth: 0,
    ...paperTexture("sheet"),
    ...paperShadow("sheet"),
  },
  networkCardWide: {
    flexBasis: 300,
    flexGrow: 0,
    maxWidth: 326,
    minWidth: 286,
  },
  rowActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "flex-end",
  },
  searchRowCompact: {
    minHeight: 46,
    paddingHorizontal: 12,
  },
  sectionActionsRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  skillIcon: {
    alignItems: "center",
    backgroundColor: "#E9F2E7",
    borderColor: "#C7DDC2",
    borderWidth: 1,
    borderRadius: 8,
    height: 42,
    justifyContent: "center",
    width: 42,
    ...paperShadow("strip"),
  },
  skillPill: {
    alignItems: "center",
    backgroundColor: "#F4EBDC",
    borderColor: "#D8CAB7",
    borderRadius: 3,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    minHeight: 26,
    justifyContent: "center",
    paddingRight: 8,
    ...paperTexture("sheet"),
    ...paperShadow("strip"),
  },
  skillPillEdge: {
    alignSelf: "stretch",
    backgroundColor: "#D7C8B5",
    borderRightColor: "rgba(255, 255, 255, 0.54)",
    borderRightWidth: 1,
    width: 4,
  },
  skillPillText: {
    color: palette.text,
    fontSize: 11,
    fontWeight: "900",
  },
  snapshotAction: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  snapshotAvatar: {
    alignItems: "center",
    backgroundColor: "#EAF2FF",
    borderColor: "#D2DDF1",
    borderWidth: 1,
    borderRadius: 8,
    height: 38,
    justifyContent: "center",
    width: 38,
    ...paperShadow("strip"),
  },
  snapshotAvatarMentor: {
    backgroundColor: "#F0E8FF",
    borderColor: "#D8C6FF",
  },
  snapshotEmpty: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  snapshotHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  snapshotList: {
    gap: 8,
  },
  snapshotMeta: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
  },
  snapshotName: {
    color: palette.text,
    fontSize: 13,
    fontWeight: "900",
    lineHeight: 17,
  },
  snapshotRow: {
    alignItems: "center",
    backgroundColor: "#FBF6EE",
    borderBottomColor: "#D8CAB8",
    borderBottomWidth: 2,
    borderColor: "#E0D4C5",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    minHeight: 58,
    padding: 9,
    ...paperTexture("sheet"),
  },
  snapshotTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "900",
  },
  statusStack: {
    alignItems: "flex-end",
    gap: 6,
  },
  statusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  textArea: {
    minHeight: 96,
    paddingTop: 12,
  },
  toolbar: {
    alignItems: "flex-start",
    gap: 10,
  },
  toolbarWide: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
  },
  twoColumn: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
});
